version: 0.2
        
phases:
    install:
        commands:
            - aws --version
            - git --version
            - docker --version
    pre_build:
        commands:
            - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 451981949438.dkr.ecr.us-east-1.amazonaws.com
            - COMMIT_ID=$(git rev-parse --short HEAD)
    build:
        commands:
            - docker build -t 451981949438.dkr.ecr.us-east-1.amazonaws.com/nginx:latest ./nginx
            - docker build -t 451981949438.dkr.ecr.us-east-1.amazonaws.com/apache:latest ./apache
            - docker tag 451981949438.dkr.ecr.us-east-1.amazonaws.com/nginx:latest 451981949438.dkr.ecr.us-east-1.amazonaws.com/nginx:latest:$COMMIT_ID
            - docker tag 451981949438.dkr.ecr.us-east-1.amazonaws.com/apache:latest 451981949438.dkr.ecr.us-east-1.amazonaws.com/apache:latest:$COMMIT_ID
    post_build:
        commands:
            - docker push 451981949438.dkr.ecr.us-east-1.amazonaws.com/nginx:latest
            - docker push 451981949438.dkr.ecr.us-east-1.amazonaws.com/nginx:latest:$COMMIT_ID
            - docker push 451981949438.dkr.ecr.us-east-1.amazonaws.com/apache:latest
            - docker push 451981949438.dkr.ecr.us-east-1.amazonaws.com/apache:latest:$COMMIT_ID