version: 1.7.0
services:
  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ~/nginx.conf:/etc/nginx/nginx.conf
      
  apache:
    image: httpd:alpine
    ports:
      - 83:80
    volumes:
      - ~/apache:/etc/apache2